import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "E-Commerce Hayata",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="antialiased"
      >
        <Toaster
          position="top-center" // Posisi notifikasi bisa diubah (top-right, bottom-center, dll)
          reverseOrder={false}
        />
        {children}
      </body>
    </html>
  );
}
